# Generated by Django 3.0 on 2022-10-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtrainermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('tage', models.IntegerField()),
                ('tphone', models.IntegerField()),
                ('temail', models.EmailField(max_length=25)),
            ],
        ),
    ]
