# Generated by Django 3.0 on 2022-10-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221022_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainerloginmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
